name: Train LLM
on:
  push:
    branches:
      - dev
  pull_requests:
      - main


jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # Step-1 Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # You can choose the Python version here

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file for dependencies

      # Step 4: Run the training script
      - name: Run train.py
        run: |
          python train.py  # This assumes that train.py and train.csv are in the root directory of your repo